### ISSUE TITLE
Detect file changes

### ISSUE THREAD

**Issue by ashokgelal** [42Squares/LightPaper#18]
_From @deadlyicon on July 18, 2014 16:52_

I'd like to be able to go edit a file open in LightPaper and have those changes auto update in light paper. Using it as a live preview. Can you make LightPaper detect changes to open files and auto update?

_Copied from original issue: AwsmApps/LightPaper-Support#34_

**Comment by deadlyicon** [comment]
So no?

**Comment by ashokgelal** [comment]
Just not yet. I'm preparing on ver 1.0 release (see [release notes here](https://github.com/42Squares/LightPaper/blob/master/ReleaseNotes%20-%201.0.md)). Once it is out, I will start working on this and few other feature requests.

**Comment by ashokgelal** [comment]
This has now been resolved in 1.1. See [full release notes here].(https://github.com/42Squares/LightPaper/blob/master/WhatsNew/ver1.1.md)

**Comment by deadlyicon** [comment]
![cheer](https://media0.giphy.com/media/KHZnqcihnb5XG/200.gif)
