### ISSUE TITLE
Error when adding a script asset

### ISSUE THREAD

**Issue by timpulver** [42Squares/LightPaper#36]
I just tried to add `https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css` which gives me the error `No such asset exists. Check the URL.`.  
The file *does* exist.

**Comment by ashokgelal** [comment]
Seems to be working fine for me. May be the server was down in that moment?

Also, you can always ignore the error and just add anyway.

**Comment by timpulver** [comment]
I checked in Chrome and it was working, okay will add it anyways.

Btw. do I have to do anything else than including the CSS to make [Font Awesome](https://fortawesome.github.io/Font-Awesome/) work?

Having this code does not show an icon:

`<i class="fa fa-camera-retro"></i> fa-camera-retro`

**Comment by timpulver** [comment]
Now it’s working. Had to re-add the CDN.
