### ISSUE TITLE
Disallow renaming shadow notes

### ISSUE THREAD

**Issue by timpulver** [42Squares/LightPaper#38]
Currently shadow notes can be renamed, but the name gets overwritten on next save (which makes sense).

<img width="245" alt="bildschirmfoto 2016-01-18 um 21 31 28" src="https://cloud.githubusercontent.com/assets/1055819/12402064/e3122fec-be2a-11e5-94a2-12923a0213f3.png">

**Comment by ashokgelal** [comment]
This is actually a bug; will be fixed in the next release. I'm going to allow renaming -- more power to the users.

**Comment by timpulver** [comment]
Will it be possible to have different notes per app then?
E.g. I would like to store references on how to use [mermaid](https://github.com/knsv/mermaid) and probably there will be lots more small chunks of information useful in the context of LightPaper.

**Comment by ashokgelal** [comment]
This is an interesting use case. I haven't thought about it. We'll see.

**Comment by ashokgelal** [comment]
Renaming issue should be resolved in 1.2.2 pre-release. Do you mind trying it out and let me know?

**Comment by timpulver** [comment]
Yes, renaming works now.
