### ISSUE TITLE
TOC Generation

### ISSUE THREAD

**Issue by timpulver** [42Squares/LightPaper#39]
It would be great if LightPaper would automatically show a table of contents with clickable links to jump within the current document!

![lightpaper-toc-concept](https://cloud.githubusercontent.com/assets/1055819/12403270/36be40d8-be33-11e5-9bcb-ea4dedfb6945.png)

**Comment by timpulver** [comment]
Just found out about the `Enable Preview Outline` feature. :+1: 

Would be great if the ordering was right, tho, so instead of 

```
H1 1
H1 2
H2 1.1
H2 1.2
H3 1.1.1
```

…having this:

```
H1 1
H2 1.1
H3 1.1.1
H2 1.2
H1 2
```

**Comment by ashokgelal** [comment]
This is actually one of the top items on my backlog. I am trying to come up with a way to support this without compromising the performance.

**Comment by ashokgelal** [comment]
Added in 1.3 beta. Here is the changelog for 1.3: https://github.com/42Squares/LightPaper/blob/master/WhatsNew/ver1.3.md

Please give it a try and let me know.

**Comment by marcinfwisniowski** [comment]
I would like to see this feature more related to the document rather than to the App it self.

I would like to see a tool like add TOC to the document. So I can Generate PDFs with TOC's

**Comment by mmatti** [comment]
Yup, what marcinfwisniowski said: TOCs (optionally) integrated with PDFs would be a wonderful feature. Would need to reflect CSS styling by the user, however.

**Comment by mmatti** [comment]
Just realized I may have muddied things by invoking CSS. Was thinking of a linked TOC at the top of a PDF document, where appearance would matter. But the bigger goal would be completely integrated TOCs, like what you get in the sidebar of Preview when you select View > Table of Contents. That would be enormously helpful in my deliverables ... has already come up in a request from a person on our team.

**Comment by timpulver** [comment]
I agree, having a generated TOC in the PDF would be nice as well!

About the preview-TOC:

Would be nice if you would get rid of «H1», «H2» and so on, having just the headlines in correct order typographically styled (H1 is bigger than H2 and so on would be perfect), so something like this:

preview-TOC:

```
# Lorem
## Ipsum
### Maecenas
#### Sit amet
## Sed diam eget
## Risus varius
```

**Comment by ashokgelal** [comment]
Does a someone has a sample document as a starting point for TOC support? Need some time to think about the UI that goes with creating a TOC.

Also, it would be nice if you can create a different ticket so that we can close this when we push 1.3. And I can get individual feedbacks on other tickets when I fix/add them. I think TOC that @marcinfwisniowski mentioned requires a different ticket. And Preview Outline TOC requires a different ticket.
