### ISSUE TITLE
Allow multiple folders in folder view (side pane)

### ISSUE THREAD

**Issue by timpulver** [42Squares/LightPaper#41]
<img width="237" alt="bildschirmfoto 2016-01-19 um 01 34 05" src="https://cloud.githubusercontent.com/assets/1055819/12406391/c296f92e-be4c-11e5-9264-b711a86233db.png">

I have some folders with markdown files which I use often. Currently I can only have one of them in the folder view. When drag’n’dropping another one onto the pane a new windows is opened, the new folder get its place in the folder view, but the other one is gone.

**Comment by ashokgelal** [comment]
Added in 1.3 beta. Here is the changelog for 1.3: https://github.com/42Squares/LightPaper/blob/master/WhatsNew/ver1.3.md

Please give it a try and let me know.

**Comment by timpulver** [comment]
Great! Works fine!
