### ISSUE TITLE
Settings views on Retina displays

### ISSUE THREAD

**Issue by chrissimpkins** [42Squares/LightPaper#42]
The current version of LightPaper looks great guys.  Nice work on this.  Just a few quick settings view issues on MacBook Pro (Retina, 15-inch, Mid 2015) OS X 10.10.5 with LightPaper v1.2.1

<img width="517" alt="lp-1" src="https://cloud.githubusercontent.com/assets/4249591/12459641/ce8e4598-bf7d-11e5-8a0a-4af3e10267c7.png">
<img width="483" alt="lp-2" src="https://cloud.githubusercontent.com/assets/4249591/12459643/d0bb4d3e-bf7d-11e5-8ab3-c5a814754080.png">
<img width="397" alt="lp-3" src="https://cloud.githubusercontent.com/assets/4249591/12459644/d249b924-bf7d-11e5-8325-d96b0faae449.png">

**Comment by chrissimpkins** [comment]
I am also seeing the settings window snap to different widths on the various tabs.  This leads to some of the tabs folding under the `>>` icon.  Is it possible to eliminate this behavior and have it remain a single, consistent width that displays all of the settings tabs?

**Comment by ashokgelal** [comment]
Please tell me that you are using a 8k monitor ;)

I use a Retina display too and have never seen this issue. Anyway, I just pushed 1.2.2 pre-release and should take care both of the above. Do you mind trying it out and let me know?

**Comment by chrissimpkins** [comment]
I wish...

1.2.2 fixed all of the above issues.  Thanks much for the quick fix!
