### ISSUE TITLE
[v1.3 (40) Beta] Shadow Note Crashes

### ISSUE THREAD

**Issue by timpulver** [42Squares/LightPaper#45]
LightPaper crashes all the time using the shadow note feature. One issue is that creating a shadow note for a website in Chrome if there is no Chrome-root object in the side-pane fails. So I have to create a pseudo note in Chrome «Chrome» in order to create one for a specific site.

Also I’m not able to save a shadow note for a site. It does not show up, only in LightPaper mini. 
Cannot use shadow notes atm.

**Comment by ashokgelal** [comment]
I'm having hard time reproducing the crash. If it is possible can you see if deleting the notes (after saving them to file first, of course), restarting the app and then adding notes again repairs this? It feels that your notes db are in weird state. Also, I didn't have to create a pseudo note for taking notes at all.
