### ISSUE TITLE
Absolute local image paths not rendering

### ISSUE THREAD

**Issue by SteveEdson** [42Squares/LightPaper#50]
I know that this is similar to #11, however I cannot get my images to render.

My images are absolute to the server root, which is also the same as my base folder.

```md
![Example image](/images/posts/example/example-image.png)
```

Not sure if this is related, but when I open the directory tree, I can see all the folders, but sub directories do not show any images in the list, even though they appear in the finder.

Thanks.

**Comment by ashokgelal** [comment]
What version of LightPaper are you using? We made it easy to set a base URL in 1.3 alpha: https://github.com/42Squares/LightPaper/blob/master/doc/Setting%20Document%20Base%

Do you mind giving it a try and let me know?

Images (and some other files) are filtered out from the sidebar by default. You can edit the filter by going to `Preferences...>Navigator`.

**Comment by SteveEdson** [comment]
Tried with 1.2 and 1.3 alpha. My base directory has been set (right clicking and "Set as base folder") however this still doesn't work.

The image is just a `.png` which is set to be visible in the preferences, however it doesn't appear in the navigator.

**Comment by ashokgelal** [comment]
> ...My base directory has been set (right clicking and "Set as base folder") 

Did you `Document>Set Base URL>Custom Folder` from Sidebar as well?

> ...which is set to be visible in the preferences

I hope you actually got rid of ".png" from the `Preferences...>Navigator` text field

**Comment by SteveEdson** [comment]
Oh, no I didn't!

That seems a bit confusing, I would have though that "Sidebar's Root Folder" would have been the default option.

Thanks though.

**Comment by ashokgelal** [comment]
It used to be but as you can see we've added a bunch of options that you can choose from. Kind of confusing at first but once you know what each option does, it is such a powerful feature.

Also, we're going to make it so that the default is `Document>Set Base URL>Custom Folder` in final 1.3 release.

**Comment by SteveEdson** [comment]
Thanks for the help, that would be better.
