### ISSUE TITLE
Small Feature Request: Make auto scrolling sync setting persistent

### ISSUE THREAD

**Issue by mmatti** [42Squares/LightPaper#51]
Title pretty much sums it up: 96% of the time, I don't want auto scroll syncing, since it tends to be distracting. But every time I restart LightPaper, it reverts to back on.

Makes sense to have it switched on initially (brand-new installation). But once the user turns it off, it should remember that preference.

**Comment by ashokgelal** [comment]
This makes sense.

**Comment by ashokgelal** [comment]
This has been fixed in 1.3 alpha 2. Please try it out and let me know (and you can close this ticket as well).

**Comment by mmatti** [comment]
Working perfectly in 1.3a2. Thanks much.
