### ISSUE TITLE
Small Feature Request: No "Untitled" tab creation when re-opening files on restart

### ISSUE THREAD

**Issue by mmatti** [42Squares/LightPaper#52]
The latest LightPaper builds are re-opening open files from last close, which is a nice usability refinement.

However, there's still a blank "Untitled" document at the start of the previously-opened-file tabs, which isn't so helpful.

That blank "Untitled" tab makes sense if there was no open file at last exit, but if I'm returning to one or more opened files, it's almost always just clutter in the tabs.

**Comment by ashokgelal** [comment]
This has been fixed in 1.3 alpha 2. Please try it out and let me know (and you can close this ticket as well).

**Comment by mmatti** [comment]
Working well ... and one less item to click. Thanks.
