### ISSUE TITLE
Clicking an internal/named link in Preview opens a window in OS X Finder

### ISSUE THREAD

**Issue by mmatti** [42Squares/LightPaper#53]
LightPaper 1.3a2 has a new wrinkle. Links to named anchors had been working just as expected: within the Preview pane, click a link pointing to a "#anchorname" target and you jump to that location in the document. (Especially nice that LP auto-generates IDs for the H1-H6 heading levels.)

Click an internal/named anchor in Preview now, and you're surprised by OS X launching a folder window. Not so useful. Happens with both Markdown syntax and manually-entered HTML tags.

**Comment by ashokgelal** [comment]
This is confirmed to be a bug in 1.3a2. Will be fixed in the next release. Thanks for reporting.

**Comment by ashokgelal** [comment]
Fixed in 1.3beta2 (build 48). Let me know if you are still seeing the issue after updating.

**Comment by mmatti** [comment]
Working perfectly now. Thank you.
