### ISSUE TITLE
Relative images not showing up

### ISSUE THREAD

**Issue by timpulver** [42Squares/LightPaper#59]
All relative image links like `![](img/foo.png)` do not show up. I always have to open another previewer (like Marked) to view it, which is really annoying.

**Comment by ashokgelal** [comment]
Go to `Documents>Set Base URL` and select `Document's parent folder` More information here: https://github.com/42Squares/LightPaper/blob/master/doc/Setting%20Document%20Base%20URL.md

**Comment by timpulver** [comment]
Thanks!
Why don’t you automatically display relative images / allow relative links?
Also it’s confusing that this setting is not under `settings`.
