### ISSUE TITLE
Shadow notes not taking formatting

### ISSUE THREAD

**Issue by rxng** [42Squares/LightPaper#68]
Hi,

I bought this app the day I saw it. Was using Ghostnote before, but this just looked.. amazing. However, when I try and take shadow notes, it is unable to accept any bold or italics formatting - a feature I was very used to and loved in Ghostnote. Additionally, if an application has multiple windows, it doesn't remember the front most window, but I have to use the dropdown each time to get to the notes.

Considering this is the main reason I bought the app, was wondering if there is any fix for this?

**Comment by ashokgelal** [comment]
LightPaper supports markdown formatting so you have to surround it with * like \*\***bold**** and \**italic**
For multiple windows which application is it? LightPaper supports number of applications out of the box for multiple windows/ tabs support.
