### ISSUE TITLE
New version compatibility mac osx 10.9

### ISSUE THREAD

**Issue by mistergraphx** [42Squares/LightPaper#69]
Hi,

I've update my version of light paper but this version is not compatible with max os 10.9, how can i revert to the older version ? could you send me a link ?

What i'm wondering, is why the update is proposed if it's incompatible with my os ?

Thanks in advance for your answer,

**Comment by ashokgelal** [comment]
You can download the last supported version from [here]:(https://rink.hockeyapp.net/apps/789cfa8846464727ae0fdb176ec8d3c8/app_versions/15)

**Comment by mistergraphx** [comment]
Thanks
