### ISSUE TITLE
License already utilized

### ISSUE THREAD

**Issue by mbadolato** [42Squares/LightPaper#80]
I'm trying to reactive my license on a new Mac and am being told that the license is already being utilized
![screen shot 2018-05-17 at 12 57 09 pm](https://user-images.githubusercontent.com/164615/40200742-ef314430-59d1-11e8-8112-6e349886665c.png)
I tried emailing support but the two addresses I found (you don't have them on your site, BTW, making it a tad difficult) bounced back

**Comment by ashokgelal** [comment]
Please send us your email address and we’ll take care of it.

Thanks

**Comment by mbadolato** [comment]
Sent. The email the mail comes from is the email address on file with you
